[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./mc.toml" },
    { access = "read", path = "./lib/mc/mc.toml" }
]

[profile.default.compiler]
version = "0.8.24"

remappings = [
    "forge-std/=lib/forge-std/src/"
]